---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.5.17
          args:
            - --interval=30s                # bit faster than 1m
            - --source=ingress              # provide both ingress and...
            - --source=service              # service resources
            - --domain-filter=lawrjone.xyz
            - --provider=google
