---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.5.17
          args:
            - --source=ingress
            - --domain-filter=lawrjone.xyz
            - --provider=cloudflare
          env:
            - name: CF_API_EMAIL
              value: "lawrjone@gmail.com"
            # Hand-managed secret
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: api-key
