---
namespace: prometheus
commonLabels:
  app: prometheus

images:
  - name: quay.io/prometheus/prometheus
    newTag: v2.13.1

resources:
  - 00-namespace.yaml
  - 01-serviceaccount.yaml
  - 02-clusterrolebinding.yaml
  - 03-statefulset.yaml
  - 04-service.yaml
  - 05-ingress.yaml

configMapGenerator:
  - name: config
    files:
      - config/prometheus.yaml
