---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: default
data:
  agent.conf: |
    exit_after_auth = true
    pid_file = "/tmp/vault-agent.pid"

    vault {
            address = "https://vault.lawrjone.xyz"
    }

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes.primary"
            config = {
                    role = "default"
            }
        }
        sink "file" {
            config = {
                path = "/tmp/vault-token"
            }
        }
    }
