---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: "vault"
  selector:
    matchLabels:
      role: backend
  replicas: 2
  volumeClaimTemplates: []  # empty, we don't need these
  template:
    metadata:
      labels:
        role: backend
    spec:
      # Important to run with this service account, as it is bound to the GCP
      # service account via workload identities
      serviceAccountName: vault-server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  # Should be unnecessary, but kustomize doesn't add this:
                  - key: app
                    operator: In
                    values:
                      - vault
                  - key: role
                    operator: In
                    values:
                      - backend
              topologyKey: kubernetes.io/hostname
      initContainers:
        ################################################################################
        # init container
        ################################################################################
        - name: config
          image: busybox
          env:
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: gcs-bucket-name
          command: ["/bin/sh", "-c"]
          args:
            - |
              cat > /etc/vault/config/vault.hcl <<EOF
              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_cert_file = "/etc/vault/tls/tls.crt"
                tls_key_file = "/etc/vault/tls/tls.key"
                tls_min_version = "tls12"
              }
              storage "gcs" {
                bucket = "${GCS_BUCKET_NAME}"
                ha_enabled = "true"
              }
              ui = true
              EOF
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
      containers:
        ################################################################################
        # vault unsealing
        ################################################################################
        - name: vault-init
          image: gcr.io/hightowerlabs/vault-init
          imagePullPolicy: IfNotPresent
          env:
            # Locally, we want the vault client to skip TLS certificate
            # validation. We need this, as the certificate that Vault is
            # configured with only has vault.lawrjone.xyz as the hostname.
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: CHECK_INTERVAL
              value: "10"
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: gcs-bucket-name
            - name: "KMS_KEY_ID"
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: kms-key-id
        ################################################################################
        # server
        ################################################################################
        - name: vault
          image: "vault:1.2.1"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "VAULT_API_ADDR"
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: api-addr
            - name: "VAULT_CLUSTER_ADDR"
              value: "https://$(POD_IP):8201"
          args:
            - server
            - -config=/etc/vault/config/vault.hcl
            - -log-format=json
          ports:
            - name: http
              containerPort: 8200
              protocol: "TCP"
            - name: server
              containerPort: 8201
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/v1/sys/health?standbyok=true"
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            - name: vault-tls
              mountPath: /etc/vault/tls
      volumes:
        - name: vault-config
          emptyDir: {}
        - name: vault-tls
          secret:
            secretName: vault-tls
