---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: credentials
data:
  # https://console.cloud.google.com/apis/credentials?highlightClient=206046083972-ihrll67goqu4aiijbtdg5kthmpaahakg.apps.googleusercontent.com&project=lawrjone&authuser=1&orgonly=true&supportedpurview=organizationId
  GF_AUTH_GOOGLE_CLIENT_SECRET: get-value-from-link
